[package]
name = "smik-jar-tool"
version = "0.1.1"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
smik-jar-lib = { path = "../smik-jar-lib" }
log = "0.4"
env_logger = "0.11"