[package]
name = "smik-jar-tool"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
semver = "1.0.26"
smik-jar-lib = { path = "../smik-jar-lib" }
log = "0.4.27"