[package]
name = "smik-jar-tool"
description = "A command-line tool for managing versions of smik JAR files."
authors = ["Richard Neumann <neumann@paulmann.de>"]
license = "MIT"
version = "0.1.7"
edition = "2024"
publish = false
readme = "README.md"

[lints]
workspace = true

[dependencies]
clap.workspace = true
env_logger.workspace = true
log.workspace = true
smik-jar-lib.workspace = true
