[package]
name = "smik-jar-tool"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
semver = "1.0"
smik-jar-lib = { path = "../smik-jar-lib" }
log = "0.4"