[package]
name = "smik-jar-lib"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
java-properties = "2.0"
log = "0.4"
zip = { version = "4.3", no-default-features = true, features = ["deflate"] }

[lints]
workspace = true
