[package]
name = "smik-jar-lib"
description = "A library for managing versions of smik JAR files."
authors = ["Richard Neumann <neumann@paulmann.de>"]
license = "MIT"
version = "0.1.1"
edition = "2024"
publish = false
readme = "README.md"

[dependencies]
java-properties.workspace = true
log.workspace = true
tempfile.workspace = true
thiserror.workspace = true
zip.workspace = true

[lints]
workspace = true
